name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # This action follows Semver and automatically bumps your version according to your commit history
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Set up Docker Buildx ##
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR ##
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image ##
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}

      # - name: Update build.yaml
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: username/repo-name # Replace with the repository where the build.yaml file is located
      #     event-type: update-build-yaml
      #     client-payload: '{"imageTag": "${{ github.sha }}"}'
