name: Manual App Image Update

on:
  workflow_dispatch:

jobs:

  update-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set image tag
        id: tag
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update app image tag
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: rratillajr/monster-rolodex-chart
          event-type: patch-app-image-tag
          client-payload: '{"imageTag": "${{ steps.tag.outputs.short_sha }}"}'
